### ISSUE TITLE
[dingus] Permalinks appear to be broken

### ISSUE THREAD

**Issue by julien-f** [commonmark/commonmark-spec-web#15]
Example: https://spec.commonmark.org/dingus/?text=foo%20bar

When I open this link, I get the default text instead of `foo bar`.

**Comment by jgm** [comment]
That's odd -- I just clicked it and got `foo bar`.

**Comment by julien-f** [comment]
Ok...
I've tested many times and my colleague too, I'll try again tomorrow and keep you posted :-p

**Comment by jgm** [comment]
How strange. Try with the javascript console open to see if you get any relevant error messages.

**Comment by julien-f** [comment]
I did check, no messages at all.

**Comment by jgm** [comment]
OK, this is strange.  I clicked it just now, and got the default.  I clicked the back button on the browser, and clicked it again...and this time I got "foo bar".

**Comment by jgm** [comment]
But now I can't get it to give me the default. Tried in three fresh browser windows (Safari, Chrome, Firefox), and each time I get "foo bar."

**Comment by julien-f** [comment]
It appears to work and fail randomly…

I'm testing with [this](https://spec.commonmark.org/dingus/?text=%3E%20foo%0A%3E%0A%3E%20bar%0A) and [that](https://spec.commonmark.org/dingus/?text=%3E%20foo%0A%0A%3E%20bar%0A), opening on a new private window in my Firefox 69 and it *usually* does not work.

**Comment by jgm** [comment]
Probably a timing issue.  I'm not a JavaScript or browser expert by any means; maybe someone else can help debug this.  On iframe load, we get the query using `window.location`; perhaps there are cases where `window.location` isn't yet set when the iframe loads?

**Comment by NfNitLoop** [comment]
This issue still seems to be around.

I can test with julien-f's "this" and "that" links above, and they work. But if I just go to <https://spec.commonmark.org/dingus/>, I get no javascript errors but no markdown is rendered (even if I type in the box to emit some new events.)

Stranger still: If I open this link in a new tab, it works. But if I copy the URL and paste it into the URL bar of a new tab, it does not. 🤔
