### ISSUE TITLE
Four ASCII characters are repeatedly parsed incorrectly

### ISSUE THREAD

**Issue by seii** [commonmark/commonmark-spec-web#19]
According to [Example 298](https://spec.commonmark.org/0.29/#example-298), `Any ASCII punctuation character may be backslash-escaped`. The example that is shown then depicts the double quote (`"`), ampersand (`&`), left angle bracket (`<`), and right angle bracket (`>`) as their HTML-escaped equivalents instead of rendering them as ASCII characters. This pattern repeats in many other examples as well (311, 569, 591, etc.), where those four characters are depicted as their HTML-escaped version when they could be interpreted as ASCII characters instead.

I'm not sure if this is a bug in commonmark.js or a bug in the website rendering, but I discovered the behavior via the `spec.json` and `spec.txt` files for all of these examples so I'm filing it against this repository.

**Comment by jgm** [comment]
These characters must be escaped in HTML, or it's invalid HTML.

**Comment by seii** [comment]
Ah, ok. Thanks, that explains the behavior.

In case anyone stumbles across this after me, these four symbols plus the apostrophe are apparently [reserved in XML](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML) (and therefore in HTML too).
