### ISSUE TITLE
redirection from current to current version discards URL fragment

### ISSUE THREAD

**Issue by esdnm** [commonmark/commonmark-spec-web#68]
https://spec.commonmark.org/current/#example-254

gets redirected to,

https://spec.commonmark.org/0.30/

not,

https://spec.commonmark.org/0.30/#example-254

**Comment by jgm** [comment]
Currently we do this in a simple way.  current/index.html has
```html
<!DOCTYPE html>
<meta charset=utf-8>
<title>Redirecting...</title>
<link rel=canonical href="//spec.commonmark.org/0.30/">
<meta http-equiv=refresh content="0; url=//spec.commonmark.org/0.30/">
<h1>Redirecting...</h1>
<a href="//spec.commonmark.org/0.30/">Click here if you are not redirected.</a>
<script>location='//spec.commonmark.org/0.30/'</script>
```
I don't know if it's possible to redirect this way while retaining the fragment.

**Comment by esdnm** [comment]
I hope changing
```js
location='//spec.commonmark.org/0.30/'
```
to

```js
location='//spec.commonmark.org/0.30/' + window.location.hash
```

will do

**Comment by jgm** [comment]
Tried it, but it doesn't seem to be enough.  But removing the http-equiv=refresh tag seemed to do it.

**Comment by jgm** [comment]
Note: if it doesn't seem to work it may be because /current/index.html is cached in your browser.
