### ISSUE TITLE
Alternative ordered list aswer not accepted

### ISSUE THREAD

**Issue by jpJuni0r** [commonmark/commonmark-spec-web#9]
As in the screenshot below, starting every line of the list with `1.` is not accepted as an answer:

![screenshot-2018-2-19 markdown tutorial - lists](https://user-images.githubusercontent.com/5278187/36358266-f8b8b002-150b-11e8-8c86-064adc82b210.png)

**Comment by jgm** [comment]
You're not supposed to make the first line into a list item.
That's just the introduction to the list.  If you leave the
`1.` off the first line, it will be accepted.

+++ Jan-Philipp Ottmüller [Feb 18 18 15:31 ]:

**Comment by jpJuni0r** [comment]
Alright, I see. Thanks!
